### ISSUE TITLE
Adding Topee framework is not working

### ISSUE THREAD

**Issue by kiliw** [avast/topee#12]
Hey I just came across this project since I want to get an already existing chrome extension to safari. I followed the instructions but unfortunately adding the Topee framework does not work.
Either I get an error in the `SafariExtensionHandler.swift` that `Topee` is not a module or some errors due to multiple target command.
I have Xcode 11.2.1 maybe something changed in the setup and how to link frameworks? The screenshots in the readmes do look a bit different compared to my version of Xcode.

**Comment by Shinisaru** [comment]
Hi, screenshots are indeed outdated.
From your brief description, you might have trouble with swift version or the way you are linking the library.
Can you please provide exact error messages?

**Comment by pavelstudeny** [comment]
seems to be ok?
