### ISSUE TITLE
Webview is not initializing

### ISSUE THREAD

**Issue by pkaragodin** [avast/topee#14]
I’ve started Demo Extension successfully. All Tests passed. Trying to integrate Topee framework to our blank extension, and we have a trouble - looks like background scripts do not inject successfully. The Webview has started, but on page about blank. No parameters get passed to web view… Do you have any idea what are we doing wrong?

**Comment by pavelstudeny** [comment]
There could be a parse error or a crash right at the script injection. You can also cross-check your chrome API calls against http://htmlpreview.github.io/?https://github.com/avast/topee/blob/master/api.html#.

There is a debug setting that allows to inject the background script later, so you have time to attach with a debugger and see the error: https://github.com/avast/topee/commit/6832884c3ea3568a67499ce19641a41803733286

I hope this helps.
