### ISSUE TITLE
Swift 5.1.3 still not working

### ISSUE THREAD

**Issue by priyanshuchauhan** [avast/topee#15]
Reference to old issue the latest changes didn't fix topee
https://github.com/avast/topee/issues/13

**Comment by pavelstudeny** [comment]
any error message available?

**Comment by priyanshuchauhan** [comment]
"Incompatible Swift version - framework was built with 4.2 and the local version is 4.2.1"

The problem was with [Carthage issue](https://github.com/Carthage/Carthage/issues/2887)
Closing the issue here.

Cathrage solution for now:
> While the fix has been merged to master a new release has not been created. To use the latest Carthage with this fix (and others) you would need to build from master at this point.

Fix if anyone else got this issue: 
1. Clone the latest Carthage master in local
2. Install using makefile

wasted lot of time playing around with "swiftenv"

**Comment by sam-w** [comment]
For anyone watching this issue, the problem should now be fixed with the release of Carthage 0.35.0
