### ISSUE TITLE
Error dyld: Library not loaded: @rpath/libswiftAppKit.dylib

### ISSUE THREAD

**Issue by rxtxup** [avast/topee#16]
I'm getting this error in xcode when extension starts:

> dyld: Library not loaded: @rpath/libswiftAppKit.dylib
>   Referenced from: /Users/evgeniy/Library/Developer/Xcode/DerivedData/TestSafariExtension-ehhixixklzriphfdcrgmwwueygue/Build/Products/Debug/TestSafariExtension.app/Contents/PlugIns/Extension.appex/Contents/Frameworks/Topee.framework/Versions/A/Topee
>   Reason: Incompatible library version: Topee requires version 1.0.0 or later, but libswiftAppKit.dylib provides version 0.0.0
> Program ended with exit code: 9
The project was created as described in the documentation.

Also, **Always Embed Swift Standard Libraries**  is **true** in TestSafariExtension.
Xcode 10.1 Toolchain: Swift 4.2.1

**Comment by pavelstudeny** [comment]
I had a look at StackOverflow and most probably, various parts of the project are built with different Swift versions.

**Comment by rxtxup** [comment]
Also Demo project works in debug mode, but in release toolbar icon doesn't show.

**Comment by pavelstudeny** [comment]
Which version of Topee do you use? 1.x is compiled with Swift 4. Topee 2.x is compiled with Swift 5.
If the icon doesn't show in release mode, you have most probably not re-added it in Safari preferences.

**Comment by pavelstudeny** [comment]
probably, the 1/2/3 Topee major versions were the reason?
