### ISSUE TITLE
Framework was built with 4.2.1 Error Skipped

### ISSUE THREAD

**Issue by liamcharmer** [avast/topee#18]
"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)."

Using Carthage Version: 0.34.0

**Comment by pavelstudeny** [comment]
Topee 1.x is for Swift 4, Topee 2.x builds with Swift 5 (although Carthage sometimes fails unless you use the not-yet-released master of https://github.com/Carthage/Carthage).
