### ISSUE TITLE
Carthage Swift Version Incompatibility 

### ISSUE THREAD

**Issue by YanivSilberman** [avast/topee#20]
I'm getting this error when trying to install it, it's clearly an issue with my Swift version, but being completely new to xcode, would you be able to help me get around it? Is there a way to run this with incompatible versions, do I need to install a previous xcode version to have the right swift to use this framework? 

Thank you

Skipped installing topee.framework binary due to the error:
	`"Incompatible Swift version - framework was built with 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) and the local version is 5.3 (swiftlang-1200.0.28.1 clang-1200.0.30.1)."`

    Falling back to building from the source
*** Skipped building topee due to the error:
Dependency "topee" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/avast/topee/issues/new

**Comment by pavelstudeny** [comment]
Basically,
Topee 1.x is built with Swift 4.x and MacOS 10.11 or 10.12 (not sure now) compatibility.
Topee 2.x is built with Swift 5.x and MacOS 10.11 or 10.12 compatibility.
Topee 3.x is built with Swift 5.x and MacOS 10.14 compatibility

If you want to get the latest version, edit your Cartfile and change your version requirements. If this is a new project, you can safely specify 3.2.0.

Another problem is that Swift 5.x (like 5.1. and 5.3) binaries are compatible with each other, but older Carthages didn't know about it. So make sure your Carthage is up to date.

By the way, the upcoming MacOS Big Sur will come with a better support for Chrome API extensions, but you still need to use Xcode and there are also some disadvantages. So some people aim for that while other people choose Topee.

Please let me know if this helps.

**Comment by YanivSilberman** [comment]
Thanks a lot for the thoughtful and detailed answer, pointing it at 3.2.0 worked like a charm!

**Comment by pavelstudeny** [comment]
Glad to hear that!
