### ISSUE TITLE
`carthage update` failing

### ISSUE THREAD

**Issue by adam-p** [avast/topee#4]
I'm trying to follow the README instructions for using topee, and not getting very far. I haven't used Carthage before, but I think this should be working:

```
$ cat Cartfile
github https://github.com/avast/topee ~> 0.0.0

$ carthage update
Parse error: expected string after dependency type in line: github https://github.com/avast/topee ~> 0.0.0

[...add quotation marks...]

cat Cartfile
github "https://github.com/avast/topee" ~> 0.0.0

$ carthage update
*** Cloning topee
*** Checking out topee at "v0.0.7"
*** xcodebuild output can be found in /var/folders/m5/9r6jj7g57z5gkl_7441qzk440000gn/T/carthage-xcodebuild.LVjL6c.log
*** Downloading topee.framework binary at "Builds Topee using Xcode10"
***  Skipped installing topee.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

    Falling back to building from the source
*** Skipped building topee due to the error:
Dependency "topee" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/avast/topee/issues/new

[...do some googling...]

$ carthage update --no-use-binaries
*** Fetching topee
*** Checking out topee at "v0.0.7"
*** xcodebuild output can be found in /var/folders/m5/9r6jj7g57z5gkl_7441qzk440000gn/T/carthage-xcodebuild.z7BVLE.log
*** Skipped building topee due to the error:
Dependency "topee" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/avast/topee/issues/new
```

I have tried this in both a "Safari Extension App" new project and plain Cocoa app new project, with the same results.

I'm not sure what to try next (except forking and building on your demo app).

**Comment by pavelstudeny** [comment]
What is your swift version then? We try to make releases with the latest stable.
Thanks for your qestion anyway, it seems that a detailed project setup manual with screenshots is needed more than we thought. Until it is ready (probably not 2018), your idea of starting with the demo application sounds the most straightforward for initial experiments. There are more people who have started this way.

**Comment by adam-p** [comment]
My Swift is 4.2.1.

I'll try to start from the demo instead.

**Comment by cat-minhv0** [comment]
Hello @pavelstudeny , @adam-p ,

Do we have any updates to fix the problem ? My swift is version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1) Xcode 10.1 10B61.

Cat

**Comment by maio** [comment]
Thanks for verification. Feel free to open new issue if you encounter some problem.

**Comment by adam-p** [comment]
Sorry, I missed this update. Works for me, too. Thanks.
