### ISSUE TITLE
Unable to get content and background to communicate

### ISSUE THREAD

**Issue by adam-p** [avast/topee#5]
I'm going to details what I did, as there are a few problems I encountered...

1. Create a new Safari App Extension project. (Calling it "MySAE".) Use Swift.

2. Run the default code in Safari. (Visiting webkit.org so that it activates.) Everything looks fine. (Except for a log line with "Unable to load Info.plist exceptions (eGPUOverrides)". I did some research and it seems to not matter.)

3. Create a Cartfile per the README; call `carthage update`. Seems successful.

4. Add `Topee.framework` to the extension's "Linked Frameworks and Libraries". 

5. Try to run again. SIGABRT with this log:
    ```
    dyld: Library not loaded: @rpath/Topee.framework/Versions/A/Topee
      Referenced from: /Users/adam/Library/Developer/Xcode/DerivedData/MySAE-hcmmxabcnthfdsgpzehstqofyumr/Build/Products/Debug/MySAE.app/Contents/PlugIns/MySAE Extension.appex/Contents/MacOS/MySAE Extension
      Reason: image not found
    ```

6. Do some googling. Add `Topee.framework` to the app's (not extension's) "Embedded Binaries", which also adds it to the "Linked Frameworks and Libraries". Run again. Works.

7. Add `topee-content.js` as a resource (Build Phases / Copy Bundle Resources), and set it as the first script under `SFSafariContentScript` in the extension's `Info.plist`.

8. Change `SafariExtensionHandler` subclass to `TopeeSafariExtensionHandler`. (And add `import Topee`.)

9. Add `TopeeSafariBackgroundScript` to plist, with empty array.

10. Run again. Seems to work, but this message appears: "MySAE Extension[9201:55667] Backgrounds scripts are taking too long to load. Check files for possible errors". (This message is why I created a fresh project and documented it.)

11. Create an empty `background.js`; add it as a resource; add it to `TopeeSafariBackgroundScript`.

12. Run. Same result. (The "taking too long" message is there for all following tests as well.)

13. Add a `console.log` call to `background.js`. Run. Log message does _not_ appear in Xcode console.

14. Add entitlement for `com.apple.security.network.client` to the extension. (This is present in the topee demo.) Run. Log message _does_ appear in Xcode console.

15. Add the ping/pong code from the demo into the content and background scripts. So they look like this:

    `script.js`:
    ```
    console.log('ADDING LISTENER');
    chrome.runtime.onMessage.addListener(function (message, sender, sendResponse) {
      console.log('got', JSON.stringify(message), 'from the background');
      if (message.type === 'ping') {
        sendResponse('content pong #' + message.value);
        return;
      }
    });

    console.log('SENDING MESSAGE');
    chrome.runtime.sendMessage({
      type: 'ping',
      value: 1
    }, console.log.bind(console, 'first'));
    ```

    `background.js`:
    ```
    console.log('ADDING LISTENER TO BACKGROUND');
    var bgPingCount = 0;
    chrome.runtime.onMessage.addListener(function (message, sender, sendResponse) {
      console.log('GOT MESSAGE', message);
      if (message.type.indexOf('ping') != -1) {
        sendResponse("background pong #" + message.value);

        setTimeout(function () {
          chrome.tabs.sendMessage(sender.tab.id, {
            type: 'ping',
            value: ++bgPingCount
          }, {
            frameId: sender.frameId
          }, function (response) {
            console.log(response);
          })
        }, 200);
      }
    });
    ```

16. Run. In the browser console, the "ADDING LISTENER" and "SENDING MESSAGE" logs appear, but not the "got" log. In the Xcode console, the "ADDING LISTENER TO BACKGROUND" log appears, but not "GOT MESSAGE". Setting breakpoints in the browser tells the same story: no response is received from the extension background.

That's as far as I got. I can't get the content and background scripts talking, so there's not much else I can do. I hope someone has some insight.

If you just skimmed the above list, there are a few problem places: steps 6, 10, 14, 16.

**Comment by pavelstudeny** [comment]
Sounds like topee-background.js does not get loaded along with your user background.js. This should normally happen automatically. Can you check whether the resource URL is resolved at https://github.com/avast/topee/blob/master/src/Framework/Sources/Swift/Public/SafariExtensionBridge.swift#L75 and then the file is read two lines later?

**Comment by cat-minhv0** [comment]
That would be really nice if @pavelstudeny @maio give an example how we use `topee` framework as we are completely new to Xcode and Swift. Thanks you so much !

**Comment by adam-p** [comment]
@pavelstudeny I'm not sure how to step into the Topee code. The [Carthage README](https://github.com/Carthage/Carthage#getting-started) indicates that the dSYM file should be made available, but it doesn't seem to be present in the `Carthage/Build` directory. 

(I could probably remove the topee Carthage framework and put the files in directly. But that might alter the nature of the test too much.)

**Comment by cat-minhv0** [comment]
@adam-p I'm following your sample steps by steps and it is working on my machine 🎉. My `SafariExtensionHandler` was inherited from `TopeeSafariExtensionHandler` and leave it blank like `topee demo`. 

Thanks you so much @adam-p @pavelstudeny !

**Comment by adam-p** [comment]
I'll let you close this. Much of what happened was my own fault, but there might still be some useful documentation changes:

* Add `Topee.framework` to the app's (not extension's) "Embedded Binaries".
* Add entitlement for `com.apple.security.network.client` to the extension. (?)
* Make sure `messageReceived` override calls `super`.

**Comment by pavelstudeny** [comment]
Debug symbols are back in the release package, along with the binaries, in 1.3.8.
Keeping this open until a detailed manual is ready.

**Comment by pavelstudeny** [comment]
About 20%-30% of the detailed instructions is available at https://github.com/avast/topee/blob/master/documentation/wizard.md . More contents will come later. Please keep me posted if any important step was missing or any other comments.

**Comment by pavelstudeny** [comment]
Setup wizard should do now. App Store publish wizard may be added eventually. Closing.
