### ISSUE TITLE
Demo works form XCODE only

### ISSUE THREAD

**Issue by SuselMan** [avast/topee#8]
Hi! I'm sorry if I misunderstood something.
I can run the demo extension from XCODE with appex target.
I try to start it with Demo target (Xcode builds and ran Demo.app), then I open Safari (12 or 13), go to preferences and enable the extension.  Safari adds the extension icon and immediately removes it. Is it possible to run topee extension not form XCODE with appex target?
Thanks. Sorry again if it is not an issue.

**Comment by SuselMan** [comment]
Also I found the crash report `Process:               Appex [25361]
Path:                  /Users/USER/Library/Developer/Xcode/DerivedData/Topee-bqftpbydperskvfgotpxpokpzvso/Build/Products/Debug/Destroy.app/Contents/PlugIns/Appex.appex/Contents/MacOS/Appex
Identifier:            Appex
Version:               1.5.1 (382)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Appex [25361]
User ID:               502

Date/Time:             2019-09-13 20:33:06.626 +0300
OS Version:            Mac OS X 10.14.6 (18G95)
Report Version:        12
Bridge OS Version:     3.6 (16P6571)
Anonymous UUID:        F30BDE23-46DA-7914-BBFE-3B18E6F6FC10

Sleep/Wake UUID:       8BC3E151-FF69-4DF7-9EBA-982BF7A9F013

Time Awake Since Boot: 21000 seconds
Time Since Wake:       190 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Topee.framework/Versions/A/Topee
  Referenced from: /Users/USER/Library/Developer/Xcode/DerivedData/Topee-bqftpbydperskvfgotpxpokpzvso/Build/Products/Debug/Destroy.app/Contents/PlugIns/Appex.appex/Contents/MacOS/Appex
  Reason: image not found

Binary Images:
       0x108bb2000 -        0x108bb3ff3 +etonreve.pavlukhin.test.appex (1.5.1 - 382) <77497B36-BD0A-3C20-B882-E0E7B4B81E40> /Users/USER/Library/Developer/Xcode/DerivedData/Topee-bqftpbydperskvfgotpxpokpzvso/Build/Products/Debug/Destroy.app/Contents/PlugIns/Appex.appex/Contents/MacOS/Appex
       0x112f63000 -        0x112fcd70f  dyld (655.1.1) <DFC3C4AF-6F97-3B34-B18D-7DCB23F2A83A> /usr/lib/dyld

`

**Comment by SuselMan** [comment]
There was the message in safari crash logs (however safari was not crashed :smiley: ) The message was Image not found. Although the message was absolutely non-informative it was a hook to find a solution. It doesn't work if you don't include binaries of topee to your parent app target

**Comment by pavelstudeny** [comment]
Yes, by Apple design, an extension has to be always bundled in the application, together with the required frameworks. Please let us know (or send a pull request), if you found any nice way to link the framework binaries statically with the extension code.
